In [5]:
import poolparty as pp

with pp.Party() as party:
    background = pp.from_seqs(['T'*20])
    left, right = pp.breakpoint_scan(background, num_breakpoints=1, positions=[3,6,9], mode='sequential')
    insert = pp.from_seqs(['AAA'])
    barcode = pp.get_kmers(length=10, mode='random')
    oligo = left + insert + right + barcode
    party.output(oligo, name='oligo')

df = party.generate(num_complete_iterations=1, seed=42)
print(len(df))
df

3

,oligo,from_seqs.seq_name,from_seqs.seq_index,breakpoint_scan.breakpoints,get_kmers.kmer_index
0,TTTAAATTTTTTTTTTTTTTTTTCCAGTGGTAT,seq_0,0,"(3,)",339635
1,TTTTTTAAATTTTTTTTTTTTTTATGATCGATG,seq_0,0,"(6,)",232846
2,TTTTTTTTTAAATTTTTTTTTTTTTGCCAAGGG,seq_0,0,"(9,)",1020970

In [ ]:
import poolparty as pp

with pp.Party() as party:
    L = 20
    window_size = 5
    background = pp.from_seqs(['T'*L])
    positions = list(range(1, L-window_size, 3))
    left, middle_right = pp.breakpoint_scan(background, num_breakpoints=1, positions=positions, mode='sequential')
    #insert = pp.from_seqs(['A'*window_size])
    middle = middle_right[:window_size]
    right = middle_right[window_size:]
    middle_shuffled = pp.shuffle(middle, k=3, mode='random')
    oligo = left + middle_shuffled + right
    party.output(oligo, name='oligo')

df = party.generate(num_complete_iterations=1, seed=42)
print(len(df))
df

5

,oligo,from_seqs.seq_name,from_seqs.seq_index,breakpoint_scan.breakpoints
0,TAAAAATTTTTTTTTTTTTT,seq_0,0,"(1,)"
1,TTTTAAAAATTTTTTTTTTT,seq_0,0,"(4,)"
2,TTTTTTTAAAAATTTTTTTT,seq_0,0,"(7,)"
3,TTTTTTTTTTAAAAATTTTT,seq_0,0,"(10,)"
4,TTTTTTTTTTTTTAAAAATT,seq_0,0,"(13,)"

In [12]:
with pp.Party() as party:
    L = 30
    background = pp.from_seqs(['T'*L])
    positions = list(range(1, L, 3))
    left, middle, right = pp.breakpoint_scan(background, num_breakpoints=2, positions=positions, mode='sequential')
    insert1 = pp.from_seqs(['AAA'])
    insert2 = pp.from_seqs(['CCC'])
    barcode = pp.get_kmers(length=10, mode='random')
    oligo = left + insert1 + middle + insert2 + right + barcode
    party.output(oligo, name='oligo')

df = party.generate(num_complete_iterations=1, seed=42)
print(positions)
print(len(df))
df

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28]
45

,oligo,from_seqs.seq_name,from_seqs.seq_index,breakpoint_scan.breakpoints,get_kmers.kmer_index
0,TAAATTTCCCTTTTTTTTTTTTTTTTTTTTTTTTTTCGGCGCGGTA,seq_0,0,"(1, 4)",432556
1,TAAATTTTTTCCCTTTTTTTTTTTTTTTTTTTTTTTTACGGATTGG,seq_0,0,"(1, 7)",813306
2,TAAATTTTTTTTTCCCTTTTTTTTTTTTTTTTTTTTTACGAGCAAA,seq_0,0,"(1, 10)",811584
3,TAAATTTTTTTTTTTTCCCTTTTTTTTTTTTTTTTTAGAACAGTGC,seq_0,0,"(1, 13)",132281
4,TAAATTTTTTTTTTTTTTTCCCTTTTTTTTTTTTTTATCCCTTTGC,seq_0,0,"(1, 16)",219129
5,TAAATTTTTTTTTTTTTTTTTTCCCTTTTTTTTTTTTGCATTGGGG,seq_0,0,"(1, 19)",937898
6,TAAATTTTTTTTTTTTTTTTTTTTTCCCTTTTTTTTACAGCCCCTT,seq_0,0,"(1, 22)",75103
7,TAAATTTTTTTTTTTTTTTTTTTTTTTTCCCTTTTTGCATGGGTTC,seq_0,0,"(1, 25)",604861
8,TAAATTTTTTTTTTTTTTTTTTTTTTTTTTTCCCTTGTGCTGCGGG,seq_0,0,"(1, 28)",761450
9,TTTTAAATTTCCCTTTTTTTTTTTTTTTTTTTTTTTATGCAGCTAA,seq_0,0,"(4, 7)",234096
10,TTTTAAATTTTTTCCCTTTTTTTTTTTTTTTTTTTTGTTAGCAGCA,seq_0,0,"(4, 10)",772388
11,TTTTAAATTTTTTTTTCCCTTTTTTTTTTTTTTTTTATTTTGGACG,seq_0,0,"(4, 13)",261766
12,TTTTAAATTTTTTTTTTTTCCCTTTTTTTTTTTTTTGTGTAACCGG,seq_0,0,"(4, 16)",766042
13,TTTTAAATTTTTTTTTTTTTTTCCCTTTTTTTTTTTTGGCGTCAAC,seq_0,0,"(4, 19)",957249
14,TTTTAAATTTTTTTTTTTTTTTTTTCCCTTTTTTTTATCATGCGAG,seq_0,0,"(4, 22)",216674
15,TTTTAAATTTTTTTTTTTTTTTTTTTTTCCCTTTTTTCCCATTGCT,seq_0,0,"(4, 25)",873447
16,TTTTAAATTTTTTTTTTTTTTTTTTTTTTTTCCCTTCTGAGGTTTC,seq_0,0,"(4, 28)",494333
17,TTTTTTTAAATTTCCCTTTTTTTTTTTTTTTTTTTTCAGAACGACA,seq_0,0,"(7, 10)",295300
18,TTTTTTTAAATTTTTTCCCTTTTTTTTTTTTTTTTTTTGAATATGG,seq_0,0,"(7, 13)",1016634
19,TTTTTTTAAATTTTTTTTTCCCTTTTTTTTTTTTTTGAGCATGAGC,seq_0,0,"(7, 16)",562057
20,TTTTTTTAAATTTTTTTTTTTTCCCTTTTTTTTTTTACAAGAACTG,seq_0,0,"(7, 19)",67614
21,TTTTTTTAAATTTTTTTTTTTTTTTCCCTTTTTTTTACTATCCGAG,seq_0,0,"(7, 22)",118114
22,TTTTTTTAAATTTTTTTTTTTTTTTTTTCCCTTTTTCGCTCAGCAA,seq_0,0,"(7, 25)",423056
23,TTTTTTTAAATTTTTTTTTTTTTTTTTTTTTCCCTTTATACATAGT,seq_0,0,"(7, 28)",836811
24,TTTTTTTTTTAAATTTCCCTTTTTTTTTTTTTTTTTACGATACTCG,seq_0,0,"(10, 13)",101494
25,TTTTTTTTTTAAATTTTTTCCCTTTTTTTTTTTTTTTTGTTCAAAC,seq_0,0,"(10, 16)",1031425
26,TTTTTTTTTTAAATTTTTTTTTCCCTTTTTTTTTTTGTATATGGCC,seq_0,0,"(10, 19)",734117
27,TTTTTTTTTTAAATTTTTTTTTTTTCCCTTTTTTTTGTTATGCGTG,seq_0,0,"(10, 22)",773742
28,TTTTTTTTTTAAATTTTTTTTTTTTTTTCCCTTTTTTGGTAACTTG,seq_0,0,"(10, 25)",962686
29,TTTTTTTTTTAAATTTTTTTTTTTTTTTTTTCCCTTAATGTTAGGG,seq_0,0,"(10, 28)",61226
30,TTTTTTTTTTTTTAAATTTCCCTTTTTTTTTTTTTTGATAAGCCGC,seq_0,0,"(13, 16)",574041
31,TTTTTTTTTTTTTAAATTTTTTCCCTTTTTTTTTTTCGATGTGCAA,seq_0,0,"(13, 19)",408464
32,TTTTTTTTTTTTTAAATTTTTTTTTCCCTTTTTTTTCGCAGTAGGT,seq_0,0,"(13, 22)",412459
33,TTTTTTTTTTTTTAAATTTTTTTTTTTTCCCTTTTTTATAACCTCT,seq_0,0,"(13, 25)",835959
34,TTTTTTTTTTTTTAAATTTTTTTTTTTTTTTCCCTTCAAAGTGGGG,seq_0,0,"(13, 28)",265130
35,TTTTTTTTTTTTTTTTAAATTTCCCTTTTTTTTTTTCGCGGTATCC,seq_0,0,"(16, 19)",420661
36,TTTTTTTTTTTTTTTTAAATTTTTTCCCTTTTTTTTTTAGCTTTGA,seq_0,0,"(16, 22)",993272
37,TTTTTTTTTTTTTTTTAAATTTTTTTTTCCCTTTTTTCCTCGCAGT,seq_0,0,"(16, 25)",882251
38,TTTTTTTTTTTTTTTTAAATTTTTTTTTTTTCCCTTGTTCACTCCT,seq_0,0,"(16, 28)",774615
39,TTTTTTTTTTTTTTTTTTTAAATTTCCCTTTTTTTTGGTTACGGGC,seq_0,0,"(19, 22)",717225
40,TTTTTTTTTTTTTTTTTTTAAATTTTTTCCCTTTTTCAAGAGGACC,seq_0,0,"(19, 25)",270981
41,TTTTTTTTTTTTTTTTTTTAAATTTTTTTTTCCCTTTTATCGGGTG,seq_0,0,"(19, 28)",997038
42,TTTTTTTTTTTTTTTTTTTTTTAAATTTCCCTTTTTGAAGCTATAA,seq_0,0,"(22, 25)",534320
43,TTTTTTTTTTTTTTTTTTTTTTAAATTTTTTCCCTTGCACCTAGAT,seq_0,0,"(22, 28)",595747
44,TTTTTTTTTTTTTTTTTTTTTTTTTAAATTTCCCTTTAAGGCGTTC,seq_0,0,"(25, 28)",797117

In [ ]:
with pp.Party() as party:
    L = 30
    background = pp.from_seqs(['T'*L])
    positions = list(range(1, L, 3))
    left, middle, right = pp.breakpoint_scan(background, num_breakpoints=2, positions=positions, mode='sequential')
    insert1 = pp.from_seqs(['AAA'])
    insert2 = pp.from_seqs(['CCC'])
    barcode = pp.get_kmers(length=10, mode='random')
    oligo = left + insert1 + middle + insert2 + right + barcode
    party.output(oligo, name='oligo')

df = party.generate(num_complete_iterations=1, seed=42)
print(positions)
print(len(df))
df