In [1]:
# Marker Scan Demo - Insert placeholder tags into sequences
import poolparty as pp

In [2]:
# Basic marker insertion - random position
with pp.Party() as party:
    pool = pp.marker_scan('ACGTACGT', marker='insert_site')

pool.generate_library(num_seqs=5, seed=42)

,seq,pool[1].seq,op[0]:from_seq.key.seq,pool[0].seq,pool[1].state,pool[0].state,op[1]:marker_scan.state,op[0]:from_seq.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.marker_tag,op[0]:from_seq.key.seq
0,{insert_site}ACGTACGT,{insert_site}ACGTACGT,ACGTACGT,ACGTACGT,0,0,0,0,0,{insert_site},ACGTACGT
1,ACGTAC{insert_site}GT,ACGTAC{insert_site}GT,ACGTACGT,ACGTACGT,0,0,0,0,6,{insert_site},ACGTACGT
2,ACGTA{insert_site}CGT,ACGTA{insert_site}CGT,ACGTACGT,ACGTACGT,0,0,0,0,5,{insert_site},ACGTACGT
3,ACG{insert_site}TACGT,ACG{insert_site}TACGT,ACGTACGT,ACGTACGT,0,0,0,0,3,{insert_site},ACGTACGT
4,ACG{insert_site}TACGT,ACG{insert_site}TACGT,ACGTACGT,ACGTACGT,0,0,0,0,3,{insert_site},ACGTACGT

In [3]:
# Sequential mode - enumerate all insertion positions
with pp.Party() as party:
    pool = pp.marker_scan('ACGT', marker='m', mode='sequential')

pool.generate_library(num_cycles=1)

,seq,pool[1].seq,op[0]:from_seq.key.seq,pool[0].seq,pool[1].state,pool[0].state,op[1]:marker_scan.state,op[0]:from_seq.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.marker_tag,op[0]:from_seq.key.seq
0,{m}ACGT,{m}ACGT,ACGT,ACGT,0,0,0,0,0,{m},ACGT
1,A{m}CGT,A{m}CGT,ACGT,ACGT,1,0,1,0,1,{m},ACGT
2,AC{m}GT,AC{m}GT,ACGT,ACGT,2,0,2,0,2,{m},ACGT
3,ACG{m}T,ACG{m}T,ACGT,ACGT,3,0,3,0,3,{m},ACGT
4,ACGT{m},ACGT{m},ACGT,ACGT,4,0,4,0,4,{m},ACGT

In [4]:
# Custom positions - limit where markers can be inserted
with pp.Party() as party:
    pool = pp.marker_scan('ACGTACGT', marker='site', positions=[0, 4, 8], mode='sequential')

pool.generate_library(num_cycles=1)

,seq,pool[1].seq,op[0]:from_seq.key.seq,pool[0].seq,pool[1].state,pool[0].state,op[1]:marker_scan.state,op[0]:from_seq.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.marker_tag,op[0]:from_seq.key.seq
0,{site}ACGTACGT,{site}ACGTACGT,ACGTACGT,ACGTACGT,0,0,0,0,0,{site},ACGTACGT
1,ACGT{site}ACGT,ACGT{site}ACGT,ACGTACGT,ACGTACGT,1,0,1,0,1,{site},ACGTACGT
2,ACGTACGT{site},ACGTACGT{site},ACGTACGT,ACGTACGT,2,0,2,0,2,{site},ACGTACGT

In [5]:
# Using Marker objects directly
with pp.Party() as party:
    marker = pp.Marker(name='promoter')
    print(f"Marker: {marker}")
    print(f"Tag: {marker.tag}")
    pool = pp.marker_scan('ACGTACGT', marker=marker)

pool.generate_library(num_seqs=3, seed=42)

Marker: Marker(id=0, name='promoter', tag='{promoter}')
Tag: {promoter}

,seq,pool[1].seq,op[0]:from_seq.key.seq,pool[0].seq,pool[1].state,pool[0].state,op[1]:marker_scan.state,op[0]:from_seq.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.marker_tag,op[0]:from_seq.key.seq
0,{promoter}ACGTACGT,{promoter}ACGTACGT,ACGTACGT,ACGTACGT,0,0,0,0,0,{promoter},ACGTACGT
1,ACGTAC{promoter}GT,ACGTAC{promoter}GT,ACGTACGT,ACGTACGT,0,0,0,0,6,{promoter},ACGTACGT
2,ACGTA{promoter}CGT,ACGTA{promoter}CGT,ACGTACGT,ACGTACGT,0,0,0,0,5,{promoter},ACGTACGT

In [6]:
# Alphabet methods handle markers correctly
alpha = pp.get_alphabet('dna')
seq_with_marker = 'AC{marker}GT'

print(f"Sequence: {seq_with_marker}")
print(f"Actual DNA length: {alpha.get_seq_length(seq_with_marker)}")  # Excludes marker
print(f"Valid positions: {alpha.get_valid_seq_positions(seq_with_marker)}")  # Excludes marker positions

Sequence: AC{marker}GT
Actual DNA length: 4
Valid positions: [0, 1, 10, 11]

In [7]:
# Combine with other operations
with pp.Party() as party:
    marked = pp.marker_scan('ACGTACGT', marker='insert', mode='sequential')
    combined = pp.join(['5_FLANK_', marked, '_3_FLANK'])

combined.generate_library(num_seqs=5)

,seq,pool[4].seq,op[3]:from_seq.key.seq,pool[3].seq,pool[1].seq,op[0]:from_seq.key.seq,pool[0].seq,op[2]:from_seq.key.seq,pool[2].seq,pool[4].state,...,op[4]:join.state,op[3]:from_seq.state,op[1]:marker_scan.state,op[0]:from_seq.state,op[2]:from_seq.state,op[3]:from_seq.key.seq,op[1]:marker_scan.key.position,op[1]:marker_scan.key.marker_tag,op[0]:from_seq.key.seq,op[2]:from_seq.key.seq
0,5_FLANK_{insert}ACGTACGT_3_FLANK,5_FLANK_{insert}ACGTACGT_3_FLANK,_3_FLANK,_3_FLANK,{insert}ACGTACGT,ACGTACGT,ACGTACGT,5_FLANK_,5_FLANK_,0,...,0,0,0,0,0,_3_FLANK,0,{insert},ACGTACGT,5_FLANK_
1,5_FLANK_A{insert}CGTACGT_3_FLANK,5_FLANK_A{insert}CGTACGT_3_FLANK,_3_FLANK,_3_FLANK,A{insert}CGTACGT,ACGTACGT,ACGTACGT,5_FLANK_,5_FLANK_,1,...,0,0,1,0,0,_3_FLANK,1,{insert},ACGTACGT,5_FLANK_
2,5_FLANK_AC{insert}GTACGT_3_FLANK,5_FLANK_AC{insert}GTACGT_3_FLANK,_3_FLANK,_3_FLANK,AC{insert}GTACGT,ACGTACGT,ACGTACGT,5_FLANK_,5_FLANK_,2,...,0,0,2,0,0,_3_FLANK,2,{insert},ACGTACGT,5_FLANK_
3,5_FLANK_ACG{insert}TACGT_3_FLANK,5_FLANK_ACG{insert}TACGT_3_FLANK,_3_FLANK,_3_FLANK,ACG{insert}TACGT,ACGTACGT,ACGTACGT,5_FLANK_,5_FLANK_,3,...,0,0,3,0,0,_3_FLANK,3,{insert},ACGTACGT,5_FLANK_
4,5_FLANK_ACGT{insert}ACGT_3_FLANK,5_FLANK_ACGT{insert}ACGT_3_FLANK,_3_FLANK,_3_FLANK,ACGT{insert}ACGT,ACGTACGT,ACGTACGT,5_FLANK_,5_FLANK_,4,...,0,0,4,0,0,_3_FLANK,4,{insert},ACGTACGT,5_FLANK_

In [8]:
# Mark sequences multiple times.
with pp.Party() as party:
    seqs = pp.from_seqs(['A'*10, 'T'*10])
    marked1 = pp.marker_scan(seqs, marker='ins1')
    marked2 = pp.marker_scan(marked1, marker='ins2')

marked2.print_tree()
marked2.generate_library(num_seqs=20, seed=42, report_pool_seqs=False, report_pool_states=False, report_op_states=False)

pool[2] (pool, n=1)
└── op[2]:marker_scan [op=marker_scan, mode=random, n=1]
    └── pool[1] (pool, n=1)
        └── op[1]:marker_scan [op=marker_scan, mode=random, n=1]
            └── pool[0] (pool, n=1)
                └── op[0]:from_seqs [op=from_seqs, mode=random, n=1]

,seq,op[2]:marker_scan.key.position,op[2]:marker_scan.key.marker_tag,op[1]:marker_scan.key.position,op[1]:marker_scan.key.marker_tag,op[0]:from_seqs.key.seq_name,op[0]:from_seqs.key.seq_index
0,AAAAAAA{ins2}A{ins1}AA,7,{ins2},8,{ins1},seq_0,0
1,AAAA{ins1}AAAAA{ins2}A,9,{ins2},4,{ins1},seq_0,0
2,AA{ins2}AAAAA{ins1}AAA,2,{ins2},7,{ins1},seq_0,0
3,AAAAA{ins1}AAAAA{ins2},10,{ins2},5,{ins1},seq_0,0
4,TTTTTTT{ins2}T{ins1}TT,7,{ins2},8,{ins1},seq_1,1
5,T{ins2}TTTT{ins1}TTTTT,1,{ins2},5,{ins1},seq_1,1
6,TTTT{ins1}T{ins2}TTTTT,5,{ins2},4,{ins1},seq_1,1
7,AA{ins1}AAAAAAAA{ins2},10,{ins2},2,{ins1},seq_0,0
8,TTTT{ins2}TTT{ins1}TTT,4,{ins2},7,{ins1},seq_1,1
9,TTTT{ins2}T{ins1}TTTTT,4,{ins2},5,{ins1},seq_1,1
10,A{ins2}A{ins1}AAAAAAAA,1,{ins2},2,{ins1},seq_0,0
11,{ins2}TTTTTTTTT{ins1}T,0,{ins2},9,{ins1},seq_1,1
12,TTT{ins2}TTTTTT{ins1}T,3,{ins2},9,{ins1},seq_1,1
13,T{ins1}TTTTTTT{ins2}TT,8,{ins2},1,{ins1},seq_1,1
14,{ins2}TTT{ins1}TTTTTTT,0,{ins2},3,{ins1},seq_1,1
15,TTTT{ins1}TTTTT{ins2}T,9,{ins2},4,{ins1},seq_1,1
16,TTTTTTTT{ins1}{ins2}TT,8,{ins2},8,{ins1},seq_1,1
17,AAAA{ins1}A{ins2}AAAAA,5,{ins2},4,{ins1},seq_0,0
18,{ins1}AAAAAA{ins2}AAAA,6,{ins2},0,{ins1},seq_0,0
19,AAAAAAA{ins2}A{ins1}AA,7,{ins2},8,{ins1},seq_0,0