In [1]:
# Random sampling from uniform probability matrix
import poolparty as pp
import pandas as pd

# 4-position motif with equal probabilities
prob_df = pd.DataFrame({'A': [0.25]*4, 'C': [0.25]*4, 'G': [0.25]*4, 'T': [0.25]*4})
with pp.Party() as party:
    pool = pp.from_prob_motif(prob_df, mode='random').named('uniform')
df = pool.generate_seqs(num_seqs=10, seed=42)
df

    seq uniform.seq  uniform.state  uniform.op.state uniform.op.key.prob_state
0  TCTG        TCTG              0                 0              [3, 1, 3, 2]
1  ATTT        ATTT              0                 0              [0, 3, 3, 3]
2  ACCT        ACCT              0                 0              [0, 1, 1, 3]
3  GTCA        GTCA              0                 0              [2, 3, 1, 0]
4  GATG        GATG              0                 0              [2, 0, 3, 2]
5  TCTT        TCTT              0                 0              [3, 1, 3, 3]
6  TACA        TACA              0                 0              [3, 0, 1, 0]
7  AGGT        AGGT              0                 0              [0, 2, 2, 3]
8  CCCA        CCCA              0                 0              [1, 1, 1, 0]
9  ACAG        ACAG              0                 0              [0, 1, 0, 2]

In [2]:
# Biased motif: A-rich at position 0, T-rich at position 1
prob_df = pd.DataFrame({
    'A': [0.9, 0.1], 'C': [0.03, 0.1], 'G': [0.03, 0.1], 'T': [0.04, 0.7]
})
with pp.Party() as party:
    pool = pp.from_prob_motif(prob_df, mode='random').named('biased')
df = pool.generate_seqs(num_seqs=20, seed=42)
df

   seq biased.seq  biased.state  biased.op.state biased.op.key.prob_state
0   AT         AT             0                0                   [0, 3]
1   AT         AT             0                0                   [0, 3]
2   AT         AT             0                0                   [0, 3]
3   AT         AT             0                0                   [0, 3]
4   AT         AT             0                0                   [0, 3]
5   AT         AT             0                0                   [0, 3]
6   AT         AT             0                0                   [0, 3]
7   AG         AG             0                0                   [0, 2]
8   AA         AA             0                0                   [0, 0]
9   AT         AT             0                0                   [0, 3]
10  AT         AT             0                0                   [0, 3]
11  TT         TT             0                0                   [3, 3]
12  AC         AC             0                0                   [0, 1]
13  AA         AA             0                0                   [0, 0]
14  AT         AT             0                0                   [0, 3]
15  AT         AT             0                0                   [0, 3]
16  AT         AT             0                0                   [0, 3]
17  AC         AC             0                0                   [0, 1]
18  AT         AT             0                0                   [0, 3]
19  AT         AT             0                0                   [0, 3]

In [3]:
# Joining with fixed flanks
with pp.Party() as party:
    left = pp.from_seq('ATG').named('left')
    var = pp.from_prob_motif(prob_df, mode='random').named('var')
    right = pp.from_seq('TAA').named('right')
    construct = pp.join([left, var, right]).named('construct')
df = construct.generate_seqs(num_seqs=10, seed=42)
df[['seq', 'var.seq']]

        seq var.seq
0  ATGATTAA      AT
1  ATGATTAA      AT
2  ATGATTAA      AT
3  ATGATTAA      AT
4  ATGATTAA      AT
5  ATGATTAA      AT
6  ATGATTAA      AT
7  ATGAGTAA      AG
8  ATGAATAA      AA
9  ATGATTAA      AT