In [1]:
import poolparty as pp

In [2]:
# Basic subseq_scan: extract 4-bp subsequences at all positions (sequential mode)
with pp.Party():
    result = pp.subseq_scan('ACGTACGTACGT', seq_length=4, mode='sequential').named('result')

df = result.generate_library(num_cycles=1, seed=42)
df

,seq,result.seq,pool[1].seq,pool[0].seq,result.state,pool[1].state,pool[0].state,result.op.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,+,<_subseq>ACGT</_subseq>
1,CGTA,CGTA,None,ACGTACGTACGT,1,None,0,0,1,0,1,+,<_subseq>CGTA</_subseq>
2,GTAC,GTAC,None,ACGTACGTACGT,2,None,0,0,2,0,2,+,<_subseq>GTAC</_subseq>
3,TACG,TACG,None,ACGTACGTACGT,3,None,0,0,3,0,3,+,<_subseq>TACG</_subseq>
4,ACGT,ACGT,None,ACGTACGTACGT,4,None,0,0,4,0,4,+,<_subseq>ACGT</_subseq>
5,CGTA,CGTA,None,ACGTACGTACGT,5,None,0,0,5,0,5,+,<_subseq>CGTA</_subseq>
6,GTAC,GTAC,None,ACGTACGTACGT,6,None,0,0,6,0,6,+,<_subseq>GTAC</_subseq>
7,TACG,TACG,None,ACGTACGTACGT,7,None,0,0,7,0,7,+,<_subseq>TACG</_subseq>
8,ACGT,ACGT,None,ACGTACGTACGT,8,None,0,0,8,0,8,+,<_subseq>ACGT</_subseq>

In [7]:
# subseq_scan with specific positions
with pp.Party():
    result = pp.subseq_scan(
        'ACGTacgtACGT',
        seq_length=4,
        positions=[0, 4, 8],
        mode='sequential'
    ).named('result')

df = result.generate_library(num_cycles=2, seed=42)
df

,seq,result.seq,pool[1].seq,pool[0].seq,result.state,pool[1].state,pool[0].state,result.op.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,ACGT,ACGT,None,ACGTacgtACGT,0,None,0,0,0,0,0,+,<_subseq>ACGT</_subseq>
1,acgt,acgt,None,ACGTacgtACGT,1,None,0,0,1,0,1,+,<_subseq>acgt</_subseq>
2,ACGT,ACGT,None,ACGTacgtACGT,2,None,0,0,2,0,2,+,<_subseq>ACGT</_subseq>
3,ACGT,ACGT,None,ACGTacgtACGT,0,None,0,0,0,0,0,+,<_subseq>ACGT</_subseq>
4,acgt,acgt,None,ACGTacgtACGT,1,None,0,0,1,0,1,+,<_subseq>acgt</_subseq>
5,ACGT,ACGT,None,ACGTacgtACGT,2,None,0,0,2,0,2,+,<_subseq>ACGT</_subseq>

In [4]:
# subseq_scan with strand='-' (reverse complement of extracted region)
with pp.Party():
    result = pp.subseq_scan(
        'ACGTACGTACGT',
        seq_length=4,
        positions=[0],
        strand='-',
        mode='sequential'
    ).named('result')

df = result.generate_library(num_seqs=5, seed=42)
print("Original: ACGT (first 4 bp)")
print("Reverse complement: ACGT")
df

Original: ACGT (first 4 bp)
Reverse complement: ACGT

,seq,result.seq,pool[1].seq,pool[0].seq,result.state,pool[1].state,pool[0].state,result.op.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,-,<_subseq strand='-'>ACGT</_subseq>
1,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,-,<_subseq strand='-'>ACGT</_subseq>
2,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,-,<_subseq strand='-'>ACGT</_subseq>
3,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,-,<_subseq strand='-'>ACGT</_subseq>
4,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,-,<_subseq strand='-'>ACGT</_subseq>

In [5]:
# subseq_scan with strand='both' - scans both strands (2x states)
with pp.Party():
    result = pp.subseq_scan(
        'ACGCTTTT',
        seq_length=4,
        positions=[0,2,4],
        strand='both',
        mode='sequential'
    ).named('result')

df = result.generate_library(num_seqs=10, seed=42)
print("Position 0: ACGT on + strand, reverse complement on - strand")
df

Position 0: ACGT on + strand, reverse complement on - strand

,seq,result.seq,pool[1].seq,pool[0].seq,result.state,pool[1].state,pool[0].state,result.op.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,ACGC,ACGC,None,ACGCTTTT,0,None,0,0,0,0,0,+,<_subseq strand='+'>ACGC</_subseq>
1,GCGT,GCGT,None,ACGCTTTT,1,None,0,0,1,0,0,-,<_subseq strand='-'>ACGC</_subseq>
2,GCTT,GCTT,None,ACGCTTTT,2,None,0,0,2,0,1,+,<_subseq strand='+'>GCTT</_subseq>
3,AAGC,AAGC,None,ACGCTTTT,3,None,0,0,3,0,1,-,<_subseq strand='-'>GCTT</_subseq>
4,TTTT,TTTT,None,ACGCTTTT,4,None,0,0,4,0,2,+,<_subseq strand='+'>TTTT</_subseq>
5,AAAA,AAAA,None,ACGCTTTT,5,None,0,0,5,0,2,-,<_subseq strand='-'>TTTT</_subseq>
6,ACGC,ACGC,None,ACGCTTTT,0,None,0,0,0,0,0,+,<_subseq strand='+'>ACGC</_subseq>
7,GCGT,GCGT,None,ACGCTTTT,1,None,0,0,1,0,0,-,<_subseq strand='-'>ACGC</_subseq>
8,GCTT,GCTT,None,ACGCTTTT,2,None,0,0,2,0,1,+,<_subseq strand='+'>GCTT</_subseq>
9,AAGC,AAGC,None,ACGCTTTT,3,None,0,0,3,0,1,-,<_subseq strand='-'>GCTT</_subseq>

In [6]:
# subseq_scan with random mode (default) - samples random positions
with pp.Party():
    result = pp.subseq_scan('ACGTACGTACGT', seq_length=4).named('result')

df = result.generate_library(num_seqs=10, seed=42)
print("Random 4-bp subsequences from ACGTACGTACGT:")
df

Random 4-bp subsequences from ACGTACGTACGT:

,seq,result.seq,pool[1].seq,pool[0].seq,result.state,pool[1].state,pool[0].state,result.op.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,+,<_subseq>ACGT</_subseq>
1,GTAC,GTAC,None,ACGTACGTACGT,0,None,0,0,0,0,6,+,<_subseq>GTAC</_subseq>
2,CGTA,CGTA,None,ACGTACGTACGT,0,None,0,0,0,0,5,+,<_subseq>CGTA</_subseq>
3,TACG,TACG,None,ACGTACGTACGT,0,None,0,0,0,0,3,+,<_subseq>TACG</_subseq>
4,TACG,TACG,None,ACGTACGTACGT,0,None,0,0,0,0,3,+,<_subseq>TACG</_subseq>
5,TACG,TACG,None,ACGTACGTACGT,0,None,0,0,0,0,7,+,<_subseq>TACG</_subseq>
6,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,+,<_subseq>ACGT</_subseq>
7,GTAC,GTAC,None,ACGTACGTACGT,0,None,0,0,0,0,6,+,<_subseq>GTAC</_subseq>
8,CGTA,CGTA,None,ACGTACGTACGT,0,None,0,0,0,0,1,+,<_subseq>CGTA</_subseq>
9,ACGT,ACGT,None,ACGTACGTACGT,0,None,0,0,0,0,0,+,<_subseq>ACGT</_subseq>