In [1]:
import poolparty as pp

In [2]:
# Basic shuffle_scan: shuffle a 4-bp window across the background sequence
with pp.Party():
    result = pp.shuffle_scan('AAACGTCGTAAA', shuffle_length=4, mode='sequential', spacer_str='.').named('result')

df = result.generate_library(num_seqs=10, seed=42)
df

,seq,result.seq,pool[6].seq,pool[5].seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,...,op[5]:fixed.state,op[4]:fixed.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,.CAAA.GTCGTAAA,.CAAA.GTCGTAAA,None,.,.,None,None,None,AAACGTCGTAAA,0,...,0,0,0,0,0,0,"(3, 2, 1, 0)",0,+,<_shuf>AAAC</_shuf>
1,A.GCAA.TCGTAAA,A.GCAA.TCGTAAA,None,.,.,None,None,None,AAACGTCGTAAA,1,...,0,0,0,0,1,0,"(2, 3, 1, 0)",1,+,<_shuf>AACG</_shuf>
2,AA.ATGC.CGTAAA,AA.ATGC.CGTAAA,None,.,.,None,None,None,AAACGTCGTAAA,2,...,0,0,0,0,2,0,"(0, 3, 2, 1)",2,+,<_shuf>ACGT</_shuf>
3,AAA.TCCG.GTAAA,AAA.TCCG.GTAAA,None,.,.,None,None,None,AAACGTCGTAAA,3,...,0,0,0,0,3,0,"(2, 3, 0, 1)",3,+,<_shuf>CGTC</_shuf>
4,AAAC.CGGT.TAAA,AAAC.CGGT.TAAA,None,.,.,None,None,None,AAACGTCGTAAA,4,...,0,0,0,0,4,0,"(2, 3, 0, 1)",4,+,<_shuf>GTCG</_shuf>
5,AAACG.CTGT.AAA,AAACG.CTGT.AAA,None,.,.,None,None,None,AAACGTCGTAAA,5,...,0,0,0,0,5,0,"(1, 0, 2, 3)",5,+,<_shuf>TCGT</_shuf>
6,AAACGT.CTAG.AA,AAACGT.CTAG.AA,None,.,.,None,None,None,AAACGTCGTAAA,6,...,0,0,0,0,6,0,"(0, 3, 1, 2)",6,+,<_shuf>CGTA</_shuf>
7,AAACGTC.TGAA.A,AAACGTC.TGAA.A,None,.,.,None,None,None,AAACGTCGTAAA,7,...,0,0,0,0,7,0,"(1, 0, 2, 3)",7,+,<_shuf>GTAA</_shuf>
8,AAACGTCG.TAAA.,AAACGTCG.TAAA.,None,.,.,None,None,None,AAACGTCGTAAA,8,...,0,0,0,0,8,0,"(0, 3, 2, 1)",8,+,<_shuf>TAAA</_shuf>
9,.AAAC.GTCGTAAA,.AAAC.GTCGTAAA,None,.,.,None,None,None,AAACGTCGTAAA,0,...,0,0,0,0,0,0,"(1, 0, 2, 3)",0,+,<_shuf>AAAC</_shuf>

In [5]:
# shuffle_scan with specific positions
with pp.Party():
    result = pp.shuffle_scan(
        'AAACGTCGTAAA',
        shuffle_length=4,
        spacer_str='.',
        positions=[0, 4, 8],
        mode='sequential'
    ).named('result')

df = result.generate_library(num_seqs=10, seed=42)
df

,seq,result.seq,pool[6].seq,pool[5].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[4].seq,result.state,...,op[5]:fixed.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[4]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,.CAAA.GTCGTAAA,.CAAA.GTCGTAAA,None,.,None,None,None,AAACGTCGTAAA,.,0,...,0,0,0,0,0,0,"(3, 2, 1, 0)",0,+,<_shuf>AAAC</_shuf>
1,AAAC.GCGT.TAAA,AAAC.GCGT.TAAA,None,.,None,None,None,AAACGTCGTAAA,.,1,...,0,0,0,1,0,0,"(2, 3, 1, 0)",1,+,<_shuf>GTCG</_shuf>
2,AAACGTCG.TAAA.,AAACGTCG.TAAA.,None,.,None,None,None,AAACGTCGTAAA,.,2,...,0,0,0,2,0,0,"(0, 3, 2, 1)",2,+,<_shuf>TAAA</_shuf>
3,.ACAA.GTCGTAAA,.ACAA.GTCGTAAA,None,.,None,None,None,AAACGTCGTAAA,.,0,...,0,0,0,0,0,0,"(2, 3, 0, 1)",0,+,<_shuf>AAAC</_shuf>
4,AAAC.CGGT.TAAA,AAAC.CGGT.TAAA,None,.,None,None,None,AAACGTCGTAAA,.,1,...,0,0,0,1,0,0,"(2, 3, 0, 1)",1,+,<_shuf>GTCG</_shuf>
5,AAACGTCG.ATAA.,AAACGTCG.ATAA.,None,.,None,None,None,AAACGTCGTAAA,.,2,...,0,0,0,2,0,0,"(1, 0, 2, 3)",2,+,<_shuf>TAAA</_shuf>
6,.AACA.GTCGTAAA,.AACA.GTCGTAAA,None,.,None,None,None,AAACGTCGTAAA,.,0,...,0,0,0,0,0,0,"(0, 3, 1, 2)",0,+,<_shuf>AAAC</_shuf>
7,AAAC.TGCG.TAAA,AAAC.TGCG.TAAA,None,.,None,None,None,AAACGTCGTAAA,.,1,...,0,0,0,1,0,0,"(1, 0, 2, 3)",1,+,<_shuf>GTCG</_shuf>
8,AAACGTCG.TAAA.,AAACGTCG.TAAA.,None,.,None,None,None,AAACGTCGTAAA,.,2,...,0,0,0,2,0,0,"(0, 3, 2, 1)",2,+,<_shuf>TAAA</_shuf>
9,.AAAC.GTCGTAAA,.AAAC.GTCGTAAA,None,.,None,None,None,AAACGTCGTAAA,.,0,...,0,0,0,0,0,0,"(1, 0, 2, 3)",0,+,<_shuf>AAAC</_shuf>

In [6]:
# shuffle_scan with mark_changes to highlight the shuffled region
with pp.Party():
    result = pp.shuffle_scan(
        'AAACGTCGTAAA',
        shuffle_length=4,
        mark_changes=True
    ).named('result')

df = result.generate_library(num_seqs=10, seed=42)
df

,seq,result.seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[4].state,pool[3].state,...,result.op.state,op[4]:fixed.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,aacaGTCGTAAA,aacaGTCGTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(0, 3, 1, 2)",0,+,<_shuf>AAAC</_shuf>
1,AAAccgtGTAAA,AAAccgtGTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 2, 3, 0)",3,+,<_shuf>CGTC</_shuf>
2,AcgaaTCGTAAA,AcgaaTCGTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(2, 3, 0, 1)",1,+,<_shuf>AACG</_shuf>
3,AAACGTtgcaAA,AAACGTtgcaAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(2, 1, 0, 3)",6,+,<_shuf>CGTA</_shuf>
4,AAACgtgcTAAA,AAACgtgcTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(0, 1, 3, 2)",4,+,<_shuf>GTCG</_shuf>
5,AAACtgcgTAAA,AAACtgcgTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 0, 2, 3)",4,+,<_shuf>GTCG</_shuf>
6,AAACGttcgAAA,AAACGttcgAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(0, 2, 3, 1)",5,+,<_shuf>TCGT</_shuf>
7,AAAgcctGTAAA,AAAgcctGTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 0, 3, 2)",3,+,<_shuf>CGTC</_shuf>
8,AAACtgcgTAAA,AAACtgcgTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 0, 2, 3)",4,+,<_shuf>GTCG</_shuf>
9,AAtgcaCGTAAA,AAtgcaCGTAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(3, 2, 1, 0)",2,+,<_shuf>ACGT</_shuf>

In [7]:
# Using scan() directly with action='shuffle'
with pp.Party():
    result = pp.scan(
        action='shuffle',
        bg_pool='AAACGTCGTAAA',
        shuffle_length=6,
        positions=[3],
        mark_changes=True
    ).named('result')

df = result.generate_library(num_seqs=10, seed=42)
df

,seq,result.seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[4].state,pool[3].state,...,result.op.state,op[4]:fixed.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,AAActtggcAAA,AAActtggcAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(5, 4, 1, 0, 3, 2)",0,+,<_shuf>CGTCGT</_shuf>
1,AAAtgcgctAAA,AAAtgcgctAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(2, 3, 0, 4, 1, 5)",0,+,<_shuf>CGTCGT</_shuf>
2,AAAtgtccgAAA,AAAtgtccgAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(4, 5, 2, 3, 1, 0)",0,+,<_shuf>CGTCGT</_shuf>
3,AAAgctctgAAA,AAAgctctgAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 5, 2, 3, 0, 4)",0,+,<_shuf>CGTCGT</_shuf>
4,AAAtcgtcgAAA,AAAtcgtcgAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 5, 3, 4, 2, 0)",0,+,<_shuf>CGTCGT</_shuf>
5,AAAgctgctAAA,AAAgctgctAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(1, 0, 5, 4, 3, 2)",0,+,<_shuf>CGTCGT</_shuf>
6,AAAtctgcgAAA,AAAtctgcgAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(4, 3, 2, 1, 5, 0)",0,+,<_shuf>CGTCGT</_shuf>
7,AAAtgccgtAAA,AAAtgccgtAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(2, 1, 0, 3, 4, 5)",0,+,<_shuf>CGTCGT</_shuf>
8,AAAttgcgcAAA,AAAttgcgcAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(5, 2, 1, 3, 4, 0)",0,+,<_shuf>CGTCGT</_shuf>
9,AAAggtctcAAA,AAAggtctcAAA,None,None,None,None,AAACGTCGTAAA,0,None,None,...,0,0,0,0,0,0,"(5, 0, 4, 3, 1, 2)",0,+,<_shuf>CGTCGT</_shuf>

In [8]:
# Verify shuffled region contains same characters (just reordered)
with pp.Party():
    result = pp.shuffle_scan(
        'AAACGTCGTAAA',
        shuffle_length=4,
        positions=[3]
    ).named('result')

df = result.generate_library(num_seqs=20, seed=42)
shuffled_regions = [seq[3:7] for seq in df['seq']]
print("Shuffled regions (all should contain same chars as 'CGTC'):")
for region in shuffled_regions[:10]:
    print(f"  {region} -> sorted: {''.join(sorted(region))}")

Shuffled regions (all should contain same chars as 'CGTC'):
  CTGC -> sorted: CCGT
  CTCG -> sorted: CCGT
  CCTG -> sorted: CCGT
  TCCG -> sorted: CCGT
  TCCG -> sorted: CCGT
  GCTC -> sorted: CCGT
  CTCG -> sorted: CCGT
  GCTC -> sorted: CCGT
  CCTG -> sorted: CCGT
  GCTC -> sorted: CCGT