In [1]:
# Marker-based scan architecture demo
# insertion_scan, replacement_scan, and deletion_scan now use marker_scan internally

import poolparty as pp

In [2]:
# insertion_scan: inserts a sequence at scanning positions
# Internally uses marker_scan (zero-length marker) + replace_marker_content

with pp.Party() as party:
    bg = pp.from_seq('AAAAAAAAAA')
    ins = pp.from_seq('GGG')
    result = pp.insertion_scan(bg, ins, mode='sequential').named('result')

df = result.generate_seqs(num_complete_iterations=1)
df

,seq,result.seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[2].state,pool[1].state,pool[0].state,result.op.state,op[2]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:marker_scan.key.position,op[2]:marker_scan.key.strand,op[2]:marker_scan.key.marker_tag
0,GGGAAAAAAAAAA,GGGAAAAAAAAAA,<_ins/>AAAAAAAAAA,GGG,AAAAAAAAAA,0,0,0,0,0,0,0,0,0,+,<_ins/>
1,AGGGAAAAAAAAA,AGGGAAAAAAAAA,A<_ins/>AAAAAAAAA,GGG,AAAAAAAAAA,1,1,0,0,0,1,0,0,1,+,<_ins/>
2,AAGGGAAAAAAAA,AAGGGAAAAAAAA,AA<_ins/>AAAAAAAA,GGG,AAAAAAAAAA,2,2,0,0,0,2,0,0,2,+,<_ins/>
3,AAAGGGAAAAAAA,AAAGGGAAAAAAA,AAA<_ins/>AAAAAAA,GGG,AAAAAAAAAA,3,3,0,0,0,3,0,0,3,+,<_ins/>
4,AAAAGGGAAAAAA,AAAAGGGAAAAAA,AAAA<_ins/>AAAAAA,GGG,AAAAAAAAAA,4,4,0,0,0,4,0,0,4,+,<_ins/>
5,AAAAAGGGAAAAA,AAAAAGGGAAAAA,AAAAA<_ins/>AAAAA,GGG,AAAAAAAAAA,5,5,0,0,0,5,0,0,5,+,<_ins/>
6,AAAAAAGGGAAAA,AAAAAAGGGAAAA,AAAAAA<_ins/>AAAA,GGG,AAAAAAAAAA,6,6,0,0,0,6,0,0,6,+,<_ins/>
7,AAAAAAAGGGAAA,AAAAAAAGGGAAA,AAAAAAA<_ins/>AAA,GGG,AAAAAAAAAA,7,7,0,0,0,7,0,0,7,+,<_ins/>
8,AAAAAAAAGGGAA,AAAAAAAAGGGAA,AAAAAAAA<_ins/>AA,GGG,AAAAAAAAAA,8,8,0,0,0,8,0,0,8,+,<_ins/>
9,AAAAAAAAAGGGA,AAAAAAAAAGGGA,AAAAAAAAA<_ins/>A,GGG,AAAAAAAAAA,9,9,0,0,0,9,0,0,9,+,<_ins/>
10,AAAAAAAAAAGGG,AAAAAAAAAAGGG,AAAAAAAAAA<_ins/>,GGG,AAAAAAAAAA,10,10,0,0,0,10,0,0,10,+,<_ins/>

In [3]:
# replacement_scan: replaces a segment at scanning positions
# Internally uses marker_scan (region marker) + replace_marker_content

with pp.Party() as party:
    bg = pp.from_seq('AAAAAAAAAA')
    ins = pp.from_seq('GGG')
    result = pp.replacement_scan(bg, ins, mode='sequential').named('result')

df = result.generate_seqs(num_complete_iterations=1)
df

,seq,result.seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[2].state,pool[1].state,pool[0].state,result.op.state,op[2]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:marker_scan.key.position,op[2]:marker_scan.key.strand,op[2]:marker_scan.key.marker_tag
0,GGGAAAAAAA,GGGAAAAAAA,<_rep>AAA</_rep>AAAAAAA,GGG,AAAAAAAAAA,0,0,0,0,0,0,0,0,0,+,<_rep>AAA</_rep>
1,AGGGAAAAAA,AGGGAAAAAA,A<_rep>AAA</_rep>AAAAAA,GGG,AAAAAAAAAA,1,1,0,0,0,1,0,0,1,+,<_rep>AAA</_rep>
2,AAGGGAAAAA,AAGGGAAAAA,AA<_rep>AAA</_rep>AAAAA,GGG,AAAAAAAAAA,2,2,0,0,0,2,0,0,2,+,<_rep>AAA</_rep>
3,AAAGGGAAAA,AAAGGGAAAA,AAA<_rep>AAA</_rep>AAAA,GGG,AAAAAAAAAA,3,3,0,0,0,3,0,0,3,+,<_rep>AAA</_rep>
4,AAAAGGGAAA,AAAAGGGAAA,AAAA<_rep>AAA</_rep>AAA,GGG,AAAAAAAAAA,4,4,0,0,0,4,0,0,4,+,<_rep>AAA</_rep>
5,AAAAAGGGAA,AAAAAGGGAA,AAAAA<_rep>AAA</_rep>AA,GGG,AAAAAAAAAA,5,5,0,0,0,5,0,0,5,+,<_rep>AAA</_rep>
6,AAAAAAGGGA,AAAAAAGGGA,AAAAAA<_rep>AAA</_rep>A,GGG,AAAAAAAAAA,6,6,0,0,0,6,0,0,6,+,<_rep>AAA</_rep>
7,AAAAAAAGGG,AAAAAAAGGG,AAAAAAA<_rep>AAA</_rep>,GGG,AAAAAAAAAA,7,7,0,0,0,7,0,0,7,+,<_rep>AAA</_rep>

In [4]:
# deletion_scan: deletes a segment at scanning positions
# Internally uses marker_scan (region marker) + replace_marker_content

with pp.Party() as party:
    bg = pp.from_seq('AAAAAAAAAA')
    result = pp.deletion_scan(bg, deletion_length=3, mode='sequential').named('result')

df = result.generate_seqs(num_complete_iterations=1)
df

,seq,result.seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[2].state,pool[1].state,pool[0].state,result.op.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,---AAAAAAA,---AAAAAAA,---,<_del>AAA</_del>AAAAAAA,AAAAAAAAAA,0,0,0,0,0,0,0,0,0,+,<_del>AAA</_del>
1,A---AAAAAA,A---AAAAAA,---,A<_del>AAA</_del>AAAAAA,AAAAAAAAAA,1,0,1,0,0,0,1,0,1,+,<_del>AAA</_del>
2,AA---AAAAA,AA---AAAAA,---,AA<_del>AAA</_del>AAAAA,AAAAAAAAAA,2,0,2,0,0,0,2,0,2,+,<_del>AAA</_del>
3,AAA---AAAA,AAA---AAAA,---,AAA<_del>AAA</_del>AAAA,AAAAAAAAAA,3,0,3,0,0,0,3,0,3,+,<_del>AAA</_del>
4,AAAA---AAA,AAAA---AAA,---,AAAA<_del>AAA</_del>AAA,AAAAAAAAAA,4,0,4,0,0,0,4,0,4,+,<_del>AAA</_del>
5,AAAAA---AA,AAAAA---AA,---,AAAAA<_del>AAA</_del>AA,AAAAAAAAAA,5,0,5,0,0,0,5,0,5,+,<_del>AAA</_del>
6,AAAAAA---A,AAAAAA---A,---,AAAAAA<_del>AAA</_del>A,AAAAAAAAAA,6,0,6,0,0,0,6,0,6,+,<_del>AAA</_del>
7,AAAAAAA---,AAAAAAA---,---,AAAAAAA<_del>AAA</_del>,AAAAAAAAAA,7,0,7,0,0,0,7,0,7,+,<_del>AAA</_del>

In [6]:
# deletion_scan with deletion_marker=None removes segment entirely

with pp.Party() as party:
    bg = pp.from_seq('ACGTACGTACGT')
    result = pp.deletion_scan(bg, deletion_length=3, deletion_marker=None, mode='sequential').named('result')

df = result.generate_seqs(num_complete_iterations=1)
df

,seq,result.seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[2].state,pool[1].state,pool[0].state,result.op.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,TACGTACGT,TACGTACGT,,<_del>ACG</_del>TACGTACGT,ACGTACGTACGT,0,0,0,0,0,0,0,0,0,+,<_del>ACG</_del>
1,AACGTACGT,AACGTACGT,,A<_del>CGT</_del>ACGTACGT,ACGTACGTACGT,1,0,1,0,0,0,1,0,1,+,<_del>CGT</_del>
2,ACCGTACGT,ACCGTACGT,,AC<_del>GTA</_del>CGTACGT,ACGTACGTACGT,2,0,2,0,0,0,2,0,2,+,<_del>GTA</_del>
3,ACGGTACGT,ACGGTACGT,,ACG<_del>TAC</_del>GTACGT,ACGTACGTACGT,3,0,3,0,0,0,3,0,3,+,<_del>TAC</_del>
4,ACGTTACGT,ACGTTACGT,,ACGT<_del>ACG</_del>TACGT,ACGTACGTACGT,4,0,4,0,0,0,4,0,4,+,<_del>ACG</_del>
5,ACGTAACGT,ACGTAACGT,,ACGTA<_del>CGT</_del>ACGT,ACGTACGTACGT,5,0,5,0,0,0,5,0,5,+,<_del>CGT</_del>
6,ACGTACCGT,ACGTACCGT,,ACGTAC<_del>GTA</_del>CGT,ACGTACGTACGT,6,0,6,0,0,0,6,0,6,+,<_del>GTA</_del>
7,ACGTACGGT,ACGTACGGT,,ACGTACG<_del>TAC</_del>GT,ACGTACGTACGT,7,0,7,0,0,0,7,0,7,+,<_del>TAC</_del>
8,ACGTACGTT,ACGTACGTT,,ACGTACGT<_del>ACG</_del>T,ACGTACGTACGT,8,0,8,0,0,0,8,0,8,+,<_del>ACG</_del>
9,ACGTACGTA,ACGTACGTA,,ACGTACGTA<_del>CGT</_del>,ACGTACGTACGT,9,0,9,0,0,0,9,0,9,+,<_del>CGT</_del>

In [7]:
# spacer_str adds separators around the inserted/replaced content

with pp.Party() as party:
    bg = pp.from_seq('AAAAAAAAAA')
    ins = pp.from_seq('GGG')
    result = pp.insertion_scan(bg, ins, spacer_str='.', mode='sequential').named('result')

df = result.generate_seqs(num_complete_iterations=1)
df

,seq,result.seq,pool[2].seq,pool[0].seq,pool[5].seq,pool[4].seq,pool[1].seq,pool[3].seq,result.state,pool[2].state,...,result.op.state,op[2]:marker_scan.state,op[0]:fixed.state,op[5]:fixed.state,op[4]:fixed.state,op[1]:fixed.state,op[3]:fixed.state,op[2]:marker_scan.key.position,op[2]:marker_scan.key.strand,op[2]:marker_scan.key.marker_tag
0,.GGG.AAAAAAAAAA,.GGG.AAAAAAAAAA,<_ins/>AAAAAAAAAA,AAAAAAAAAA,.GGG.,.,GGG,.,0,0,...,0,0,0,0,0,0,0,0,+,<_ins/>
1,A.GGG.AAAAAAAAA,A.GGG.AAAAAAAAA,A<_ins/>AAAAAAAAA,AAAAAAAAAA,.GGG.,.,GGG,.,1,1,...,0,1,0,0,0,0,0,1,+,<_ins/>
2,AA.GGG.AAAAAAAA,AA.GGG.AAAAAAAA,AA<_ins/>AAAAAAAA,AAAAAAAAAA,.GGG.,.,GGG,.,2,2,...,0,2,0,0,0,0,0,2,+,<_ins/>
3,AAA.GGG.AAAAAAA,AAA.GGG.AAAAAAA,AAA<_ins/>AAAAAAA,AAAAAAAAAA,.GGG.,.,GGG,.,3,3,...,0,3,0,0,0,0,0,3,+,<_ins/>
4,AAAA.GGG.AAAAAA,AAAA.GGG.AAAAAA,AAAA<_ins/>AAAAAA,AAAAAAAAAA,.GGG.,.,GGG,.,4,4,...,0,4,0,0,0,0,0,4,+,<_ins/>
5,AAAAA.GGG.AAAAA,AAAAA.GGG.AAAAA,AAAAA<_ins/>AAAAA,AAAAAAAAAA,.GGG.,.,GGG,.,5,5,...,0,5,0,0,0,0,0,5,+,<_ins/>
6,AAAAAA.GGG.AAAA,AAAAAA.GGG.AAAA,AAAAAA<_ins/>AAAA,AAAAAAAAAA,.GGG.,.,GGG,.,6,6,...,0,6,0,0,0,0,0,6,+,<_ins/>
7,AAAAAAA.GGG.AAA,AAAAAAA.GGG.AAA,AAAAAAA<_ins/>AAA,AAAAAAAAAA,.GGG.,.,GGG,.,7,7,...,0,7,0,0,0,0,0,7,+,<_ins/>
8,AAAAAAAA.GGG.AA,AAAAAAAA.GGG.AA,AAAAAAAA<_ins/>AA,AAAAAAAAAA,.GGG.,.,GGG,.,8,8,...,0,8,0,0,0,0,0,8,+,<_ins/>
9,AAAAAAAAA.GGG.A,AAAAAAAAA.GGG.A,AAAAAAAAA<_ins/>A,AAAAAAAAAA,.GGG.,.,GGG,.,9,9,...,0,9,0,0,0,0,0,9,+,<_ins/>
10,AAAAAAAAAA.GGG.,AAAAAAAAAA.GGG.,AAAAAAAAAA<_ins/>,AAAAAAAAAA,.GGG.,.,GGG,.,10,10,...,0,10,0,0,0,0,0,10,+,<_ins/>

In [8]:
# The underlying marker_scan operation inserts XML markers at positions
# This is what powers insertion_scan, replacement_scan, and deletion_scan

with pp.Party() as party:
    bg = pp.from_seq('AAAAAAAAAA')
    marked = pp.marker_scan(bg, marker='region', marker_length=3, mode='sequential').named('marked')

df = marked.generate_seqs(num_complete_iterations=1)
df

,seq,marked.seq,pool[0].seq,marked.state,pool[0].state,marked.op.state,op[0]:fixed.state,marked.op.key.position,marked.op.key.strand,marked.op.key.marker_tag
0,<region>AAA</region>AAAAAAA,<region>AAA</region>AAAAAAA,AAAAAAAAAA,0,0,0,0,0,+,<region>AAA</region>
1,A<region>AAA</region>AAAAAA,A<region>AAA</region>AAAAAA,AAAAAAAAAA,1,0,1,0,1,+,<region>AAA</region>
2,AA<region>AAA</region>AAAAA,AA<region>AAA</region>AAAAA,AAAAAAAAAA,2,0,2,0,2,+,<region>AAA</region>
3,AAA<region>AAA</region>AAAA,AAA<region>AAA</region>AAAA,AAAAAAAAAA,3,0,3,0,3,+,<region>AAA</region>
4,AAAA<region>AAA</region>AAA,AAAA<region>AAA</region>AAA,AAAAAAAAAA,4,0,4,0,4,+,<region>AAA</region>
5,AAAAA<region>AAA</region>AA,AAAAA<region>AAA</region>AA,AAAAAAAAAA,5,0,5,0,5,+,<region>AAA</region>
6,AAAAAA<region>AAA</region>A,AAAAAA<region>AAA</region>A,AAAAAAAAAA,6,0,6,0,6,+,<region>AAA</region>
7,AAAAAAA<region>AAA</region>,AAAAAAA<region>AAA</region>,AAAAAAAAAA,7,0,7,0,7,+,<region>AAA</region>

In [9]:
# apply_at_marker transforms the content at a marked region
# This enables powerful composable operations

with pp.Party() as party:
    bg = pp.from_seq('ACGT<orf>ATGCCC</orf>TTTT')
    result = pp.apply_at_marker(bg, 'orf', pp.reverse_complement).named('result')

df = result.generate_seqs(num_seqs=1)
print(f"Original: ACGT<orf>ATGCCC</orf>TTTT")
print(f"Result:   {df['seq'].iloc[0]}")

Original: ACGT<orf>ATGCCC</orf>TTTT
Result:   ACGTGGGCATTTTT