In [1]:
import poolparty as pp

In [8]:
# Basic shuffle_scan: shuffle a 4-bp window across the background sequence
with pp.Party():
    result = pp.shuffle_scan('AAACGTCGTAAA', shuffle_length=4, mode='sequential').named('result')

df = result.generate_seqs(num_seqs=10, seed=42)
df

ConflictingStateAssignmentError: Counter 'pool[1].state' received conflicting state assignments: already set to 1, now attempting to set to 0.

In [3]:
# shuffle_scan with specific positions
with pp.Party():
    result = pp.shuffle_scan(
        'AAACGTCGTAAA',
        shuffle_length=4,
        positions=[0, 4, 8],
        mode='random'
    ).named('result')

df = result.generate_seqs(num_seqs=10, seed=42)
df

,seq,result.seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[3].state,pool[2].state,pool[1].state,pool[0].state,result.op.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,AACAGTCGTAAA,AACAGTCGTAAA,AACA,AAAC,<_shuf>AAAC</_shuf>GTCGTAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(0, 3, 1, 2)",0,+,<_shuf>AAAC</_shuf>
1,AAACGGTCTAAA,AAACGGTCTAAA,GGTC,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(1, 2, 3, 0)",1,+,<_shuf>GTCG</_shuf>
2,ACAAGTCGTAAA,ACAAGTCGTAAA,ACAA,AAAC,<_shuf>AAAC</_shuf>GTCGTAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(2, 3, 0, 1)",0,+,<_shuf>AAAC</_shuf>
3,AAACGTCGAATA,AAACGTCGAATA,AATA,TAAA,AAACGTCG<_shuf>TAAA</_shuf>,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(2, 1, 0, 3)",2,+,<_shuf>TAAA</_shuf>
4,AAACGTGCTAAA,AAACGTGCTAAA,GTGC,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(0, 1, 3, 2)",1,+,<_shuf>GTCG</_shuf>
5,AAACTGCGTAAA,AAACTGCGTAAA,TGCG,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(1, 0, 2, 3)",1,+,<_shuf>GTCG</_shuf>
6,AAACGGTCTAAA,AAACGGTCTAAA,GGTC,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(0, 2, 3, 1)",1,+,<_shuf>GTCG</_shuf>
7,AAACTGGCTAAA,AAACTGGCTAAA,TGGC,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(1, 0, 3, 2)",1,+,<_shuf>GTCG</_shuf>
8,AAACTGCGTAAA,AAACTGCGTAAA,TGCG,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(1, 0, 2, 3)",1,+,<_shuf>GTCG</_shuf>
9,CAAAGTCGTAAA,CAAAGTCGTAAA,CAAA,AAAC,<_shuf>AAAC</_shuf>GTCGTAAA,AAACGTCGTAAA,0,0,0,0,0,0,0,0,0,0,"(3, 2, 1, 0)",0,+,<_shuf>AAAC</_shuf>

In [4]:
# shuffle_scan with mark_changes to highlight the shuffled region
with pp.Party():
    result = pp.shuffle_scan(
        'AAACGTCGTAAA',
        shuffle_length=4,
        mark_changes=True
    ).named('result')

df = result.generate_seqs(num_seqs=10, seed=42)
df

,seq,result.seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[4].state,pool[3].state,...,result.op.state,op[4]:fixed.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,aacaGTCGTAAA,aacaGTCGTAAA,aaca,AACA,AAAC,<_shuf>AAAC</_shuf>GTCGTAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(0, 3, 1, 2)",0,+,<_shuf>AAAC</_shuf>
1,AAAccgtGTAAA,AAAccgtGTAAA,ccgt,CCGT,CGTC,AAA<_shuf>CGTC</_shuf>GTAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 2, 3, 0)",3,+,<_shuf>CGTC</_shuf>
2,AcgaaTCGTAAA,AcgaaTCGTAAA,cgaa,CGAA,AACG,A<_shuf>AACG</_shuf>TCGTAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(2, 3, 0, 1)",1,+,<_shuf>AACG</_shuf>
3,AAACGTtgcaAA,AAACGTtgcaAA,tgca,TGCA,CGTA,AAACGT<_shuf>CGTA</_shuf>AA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(2, 1, 0, 3)",6,+,<_shuf>CGTA</_shuf>
4,AAACgtgcTAAA,AAACgtgcTAAA,gtgc,GTGC,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(0, 1, 3, 2)",4,+,<_shuf>GTCG</_shuf>
5,AAACtgcgTAAA,AAACtgcgTAAA,tgcg,TGCG,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 0, 2, 3)",4,+,<_shuf>GTCG</_shuf>
6,AAACGttcgAAA,AAACGttcgAAA,ttcg,TTCG,TCGT,AAACG<_shuf>TCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(0, 2, 3, 1)",5,+,<_shuf>TCGT</_shuf>
7,AAAgcctGTAAA,AAAgcctGTAAA,gcct,GCCT,CGTC,AAA<_shuf>CGTC</_shuf>GTAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 0, 3, 2)",3,+,<_shuf>CGTC</_shuf>
8,AAACtgcgTAAA,AAACtgcgTAAA,tgcg,TGCG,GTCG,AAAC<_shuf>GTCG</_shuf>TAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 0, 2, 3)",4,+,<_shuf>GTCG</_shuf>
9,AAtgcaCGTAAA,AAtgcaCGTAAA,tgca,TGCA,ACGT,AA<_shuf>ACGT</_shuf>CGTAAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(3, 2, 1, 0)",2,+,<_shuf>ACGT</_shuf>

In [5]:
# Using scan() directly with action='shuffle'
with pp.Party():
    result = pp.scan(
        action='shuffle',
        bg_pool='AAACGTCGTAAA',
        shuffle_length=6,
        positions=[3],
        mark_changes=True
    ).named('result')

df = result.generate_seqs(num_seqs=10, seed=42)
df

,seq,result.seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,result.state,pool[4].state,pool[3].state,...,result.op.state,op[4]:fixed.state,op[3]:seq_shuffle.state,op[2]:fixed.state,op[1]:marker_scan.state,op[0]:fixed.state,op[3]:seq_shuffle.key.permutation,op[1]:marker_scan.key.position,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.marker_tag
0,AAActtggcAAA,AAActtggcAAA,cttggc,CTTGGC,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(5, 4, 1, 0, 3, 2)",0,+,<_shuf>CGTCGT</_shuf>
1,AAAtgcgctAAA,AAAtgcgctAAA,tgcgct,TGCGCT,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(2, 3, 0, 4, 1, 5)",0,+,<_shuf>CGTCGT</_shuf>
2,AAAtgtccgAAA,AAAtgtccgAAA,tgtccg,TGTCCG,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(4, 5, 2, 3, 1, 0)",0,+,<_shuf>CGTCGT</_shuf>
3,AAAgctctgAAA,AAAgctctgAAA,gctctg,GCTCTG,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 5, 2, 3, 0, 4)",0,+,<_shuf>CGTCGT</_shuf>
4,AAAtcgtcgAAA,AAAtcgtcgAAA,tcgtcg,TCGTCG,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 5, 3, 4, 2, 0)",0,+,<_shuf>CGTCGT</_shuf>
5,AAAgctgctAAA,AAAgctgctAAA,gctgct,GCTGCT,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(1, 0, 5, 4, 3, 2)",0,+,<_shuf>CGTCGT</_shuf>
6,AAAtctgcgAAA,AAAtctgcgAAA,tctgcg,TCTGCG,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(4, 3, 2, 1, 5, 0)",0,+,<_shuf>CGTCGT</_shuf>
7,AAAtgccgtAAA,AAAtgccgtAAA,tgccgt,TGCCGT,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(2, 1, 0, 3, 4, 5)",0,+,<_shuf>CGTCGT</_shuf>
8,AAAttgcgcAAA,AAAttgcgcAAA,ttgcgc,TTGCGC,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(5, 2, 1, 3, 4, 0)",0,+,<_shuf>CGTCGT</_shuf>
9,AAAggtctcAAA,AAAggtctcAAA,ggtctc,GGTCTC,CGTCGT,AAA<_shuf>CGTCGT</_shuf>AAA,AAACGTCGTAAA,0,0,0,...,0,0,0,0,0,0,"(5, 0, 4, 3, 1, 2)",0,+,<_shuf>CGTCGT</_shuf>

In [6]:
# Verify shuffled region contains same characters (just reordered)
with pp.Party():
    result = pp.shuffle_scan(
        'AAACGTCGTAAA',
        shuffle_length=4,
        positions=[3]
    ).named('result')

df = result.generate_seqs(num_seqs=20, seed=42)
shuffled_regions = [seq[3:7] for seq in df['seq']]
print("Shuffled regions (all should contain same chars as 'CGTC'):")
for region in shuffled_regions[:10]:
    print(f"  {region} -> sorted: {''.join(sorted(region))}")

Shuffled regions (all should contain same chars as 'CGTC'):
  CTGC -> sorted: CCGT
  CTCG -> sorted: CCGT
  CCTG -> sorted: CCGT
  TCCG -> sorted: CCGT
  TCCG -> sorted: CCGT
  GCTC -> sorted: CCGT
  CTCG -> sorted: CCGT
  GCTC -> sorted: CCGT
  CCTG -> sorted: CCGT
  GCTC -> sorted: CCGT