In [1]:
import poolparty as pp

In [2]:
# Pool.mutagenize_region() applies mutagenize() to a marked region (marker removed by default)
with pp.Party():
    bg = pp.from_seq('FLANK<target>ACGT</target>FLANK')
    result = bg.mutagenize_region('target', num_mutations=1, mark_changes=True, mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:replace_marker_content.state,op[2]:mutagenize.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:mutagenize.key.positions,op[2]:mutagenize.key.wt_chars,op[2]:mutagenize.key.mut_chars
0,FLANKcCGTFLANK,FLANKcCGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,0,None,None,0,0,0,0,0,"(0,)","(A,)","(c,)"
1,FLANKgCGTFLANK,FLANKgCGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,1,None,None,0,0,1,0,0,"(0,)","(A,)","(g,)"
2,FLANKtCGTFLANK,FLANKtCGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,2,None,None,0,0,2,0,0,"(0,)","(A,)","(t,)"
3,FLANKAaGTFLANK,FLANKAaGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,3,None,None,0,0,3,0,0,"(1,)","(C,)","(a,)"
4,FLANKAgGTFLANK,FLANKAgGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,4,None,None,0,0,4,0,0,"(1,)","(C,)","(g,)"
5,FLANKAtGTFLANK,FLANKAtGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,5,None,None,0,0,5,0,0,"(1,)","(C,)","(t,)"
6,FLANKACaTFLANK,FLANKACaTFLANK,None,None,FLANK<target>ACGT</target>FLANK,6,None,None,0,0,6,0,0,"(2,)","(G,)","(a,)"
7,FLANKACcTFLANK,FLANKACcTFLANK,None,None,FLANK<target>ACGT</target>FLANK,7,None,None,0,0,7,0,0,"(2,)","(G,)","(c,)"
8,FLANKACtTFLANK,FLANKACtTFLANK,None,None,FLANK<target>ACGT</target>FLANK,8,None,None,0,0,8,0,0,"(2,)","(G,)","(t,)"
9,FLANKACGaFLANK,FLANKACGaFLANK,None,None,FLANK<target>ACGT</target>FLANK,9,None,None,0,0,9,0,0,"(3,)","(T,)","(a,)"
10,FLANKACGcFLANK,FLANKACGcFLANK,None,None,FLANK<target>ACGT</target>FLANK,10,None,None,0,0,10,0,0,"(3,)","(T,)","(c,)"
11,FLANKACGgFLANK,FLANKACGgFLANK,None,None,FLANK<target>ACGT</target>FLANK,11,None,None,0,0,11,0,0,"(3,)","(T,)","(g,)"

In [3]:
# With remove_marker=False, the marker tags are preserved around the mutagenized content
with pp.Party():
    bg = pp.from_seq('FLANK<target>ACGT</target>FLANK')
    result = bg.mutagenize_region('target', remove_marker=False, num_mutations=1, mark_changes=True, mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:fixed.state,op[2]:mutagenize.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:mutagenize.key.positions,op[2]:mutagenize.key.wt_chars,op[2]:mutagenize.key.mut_chars
0,FLANK<target>cCGT</target>FLANK,FLANK<target>cCGT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,0,None,None,0,0,0,0,0,"(0,)","(A,)","(c,)"
1,FLANK<target>gCGT</target>FLANK,FLANK<target>gCGT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,1,None,None,0,0,1,0,0,"(0,)","(A,)","(g,)"
2,FLANK<target>tCGT</target>FLANK,FLANK<target>tCGT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,2,None,None,0,0,2,0,0,"(0,)","(A,)","(t,)"
3,FLANK<target>AaGT</target>FLANK,FLANK<target>AaGT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,3,None,None,0,0,3,0,0,"(1,)","(C,)","(a,)"
4,FLANK<target>AgGT</target>FLANK,FLANK<target>AgGT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,4,None,None,0,0,4,0,0,"(1,)","(C,)","(g,)"
5,FLANK<target>AtGT</target>FLANK,FLANK<target>AtGT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,5,None,None,0,0,5,0,0,"(1,)","(C,)","(t,)"
6,FLANK<target>ACaT</target>FLANK,FLANK<target>ACaT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,6,None,None,0,0,6,0,0,"(2,)","(G,)","(a,)"
7,FLANK<target>ACcT</target>FLANK,FLANK<target>ACcT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,7,None,None,0,0,7,0,0,"(2,)","(G,)","(c,)"
8,FLANK<target>ACtT</target>FLANK,FLANK<target>ACtT</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,8,None,None,0,0,8,0,0,"(2,)","(G,)","(t,)"
9,FLANK<target>ACGa</target>FLANK,FLANK<target>ACGa</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,9,None,None,0,0,9,0,0,"(3,)","(T,)","(a,)"
10,FLANK<target>ACGc</target>FLANK,FLANK<target>ACGc</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,10,None,None,0,0,10,0,0,"(3,)","(T,)","(c,)"
11,FLANK<target>ACGg</target>FLANK,FLANK<target>ACGg</target>FLANK,None,None,FLANK<target>ACGT</target>FLANK,11,None,None,0,0,11,0,0,"(3,)","(T,)","(g,)"

In [4]:
# Works with mutation_rate as well
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGTACGTACGT</region>TTT')
    result = bg.mutagenize_region('region', mutation_rate=0.25)
    df = result.generate_library(num_cycles=5, seed=42)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:replace_marker_content.state,op[2]:mutagenize.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:mutagenize.key.positions,op[2]:mutagenize.key.wt_chars,op[2]:mutagenize.key.mut_chars
0,AAAACGTCGGTACTGTTT,AAAACGTCGGTACTGTTT,None,None,AAA<region>ACGTACGTACGT</region>TTT,0,None,None,0,0,0,0,0,"(4, 5, 10, 11)","(A, C, G, T)","(C, G, T, G)"
1,AAAAAGTATTTACCTTTT,AAAAAGTATTTACCTTTT,None,None,AAA<region>ACGTACGTACGT</region>TTT,0,None,None,0,0,0,0,0,"(1, 5, 6, 10)","(C, C, G, G)","(A, T, T, C)"
2,AAAACATTCGTATATTTT,AAAACATTCGTATATTTT,None,None,AAA<region>ACGTACGTACGT</region>TTT,0,None,None,0,0,0,0,0,"(2, 4, 9, 10)","(G, A, C, G)","(A, T, T, A)"
3,AAATCGGATGAACGTTTT,AAATCGGATGAACGTTTT,None,None,AAA<region>ACGTACGTACGT</region>TTT,0,None,None,0,0,0,0,0,"(0, 3, 5, 7)","(A, T, C, T)","(T, G, T, A)"
4,AAATCGTTCTTACGTTTT,AAATCGTTCTTACGTTTT,None,None,AAA<region>ACGTACGTACGT</region>TTT,0,None,None,0,0,0,0,0,"(0, 4, 6)","(A, A, G)","(T, T, T)"

In [5]:
# apply_at_marker() also supports remove_marker=False for any transformation
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGT</region>TTT')
    result = bg.apply_at_marker('region', pp.reverse_complement, remove_marker=False)
    df = result.generate_library(num_cycles=1)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:fixed.state,op[2]:fixed.state,op[1]:fixed.state,op[0]:fixed.state
0,AAA<region>ACGT</region>TTT,AAA<region>ACGT</region>TTT,None,None,AAA<region>ACGT</region>TTT,0,None,None,0,0,0,0,0