In [1]:
import poolparty as pp
pp.init()

Party(outputs=[])

## Creating Pools
### from_seq

In [ ]:
pool = pp.from_seq("AAAA")
library = pool.generate_library()
print(library)

In [ ]:
wt = pp.from_seq("GCGC<promoter>TATAAA</promoter><core>ATCGATCG</core>GCGC")
print(wt.generate_library())

In [ ]:
wt      = pp.from_seq("AAAA<cre>ATCG</cre>TTTT")
mutant  = pp.from_seq("GGGG", pool=wt, region="cre")
mutant.generate_library()
#mutant.print_library()

### from_seqs

In [ ]:
pool = pp.from_seqs(["AAAA", "CCCC", "GGGG", "TTTT"], num_states=4)
pool.generate_library()

In [ ]:
pool = pp.from_seqs(
    ["ATCG", "CGTA", "GCAT"],
    mode="sequential",
)
pool.generate_library()

In [ ]:
pool = pp.from_seqs(
    ["ATCG", "CGTA", "GCAT"],
    seq_names=["wt", "mut_A", "mut_B"],
    mode="sequential",
)
pool.generate_library()

### from_fasta

In [ ]:
pool = pp.from_fasta(
    "genome.fa",
    coordinates=("chr1", 1000, 1020, "+"),
)
pool.generate_library()

In [ ]:
pool = pp.from_fasta(
    "genome.fa",
    coordinates=("chr1", 5000, 5010, "-"),
)
pool.generate_library()

In [ ]:
coords = [
    ("chr1", 1000, 1010, "+"),
    ("chr1", 5000, 5010, "-"),
    ("chr1", 200,  210,  "+"),
]
pool = pp.from_fasta("genome.fa", coordinates=coords, prefix="enh")
pool.generate_library()

In [ ]:
vector = pp.from_seq("GCGCGC<insert>XXXXXXXXXX</insert>GCGCGC")
coords = [("chr1", 1000, 1010, "+"), ("chr1", 2000, 2010, "+")]
pool   = pp.from_fasta("genome.fa", coordinates=coords,
                       pool=vector, region="insert")
pool.generate_library()

### from_iupac

In [ ]:
pool = pp.from_iupac("WN", num_states=4)
pool.generate_library()

In [ ]:
pool = pp.from_iupac("RY", mode="sequential")
pool.generate_library()

In [ ]:
pool = pp.from_iupac("NNNN", mode="sequential", num_states=8)
pool.generate_library()

In [3]:
bg   = pp.from_seq("AAAA<cre>XXX</cre>TTTT")
pool = pp.from_iupac("NNN", mode="sequential", pool=bg, region="cre")
pool.generate_library()

    name                     seq
0   None  AAAA<cre>AAA</cre>TTTT
1   None  AAAA<cre>AAC</cre>TTTT
2   None  AAAA<cre>AAG</cre>TTTT
3   None  AAAA<cre>AAT</cre>TTTT
4   None  AAAA<cre>ACA</cre>TTTT
..   ...                     ...
59  None  AAAA<cre>TGT</cre>TTTT
60  None  AAAA<cre>TTA</cre>TTTT
61  None  AAAA<cre>TTC</cre>TTTT
62  None  AAAA<cre>TTG</cre>TTTT
63  None  AAAA<cre>TTT</cre>TTTT

[64 rows x 2 columns]

### from_motif

In [ ]:
import pandas as pd

pfm = pd.DataFrame(
    {"A": [0.25, 0.25], "C": [0.25, 0.25],
     "G": [0.25, 0.25], "T": [0.25, 0.25]}
)
pool = pp.from_motif(pfm, num_states=4)

   name seq
0  None  GA
1  None  TG
2  None  GT
3  None  GG
4  None  GA
5  None  TG
6  None  GT
7  None  GG

In [29]:
pool.generate_library(num_cycles=2, seed=42)

   name seq
0  None  GA
1  None  TG
2  None  GT
3  None  GG
4  None  GA
5  None  TG
6  None  GT
7  None  GG

In [32]:
pfm = pd.DataFrame(
    {"A": [0.7, 0.1], "C": [0.1, 0.7],
     "G": [0.1, 0.1], "T": [0.1, 0.1]}
)
bg   = pp.from_seq("GCGC<insert>XX</insert>GCGC")
pool = pp.from_motif(pfm, pool=bg, region="insert", num_states=4)
pool.generate_library()

   name                          seq
0  None  GCGC<insert>AT</insert>GCGC
1  None  GCGC<insert>GC</insert>GCGC
2  None  GCGC<insert>AC</insert>GCGC
3  None  GCGC<insert>AC</insert>GCGC

### get_kmers

In [35]:
pool = pp.get_kmers(length=2, mode="sequential")
pool.generate_library()

    name seq
0   None  AA
1   None  AC
2   None  AG
3   None  AT
4   None  CA
5   None  CC
6   None  CG
7   None  CT
8   None  GA
9   None  GC
10  None  GG
11  None  GT
12  None  TA
13  None  TC
14  None  TG
15  None  TT

In [36]:
pool = pp.get_kmers(length=4, mode="random", num_states=8)
pool.generate_library()

   name   seq
0  None  GACG
1  None  ATTA
2  None  GCAG
3  None  ATTC
4  None  AAAA
5  None  ACCG
6  None  AACA
7  None  ACGA

In [37]:
pool = pp.get_kmers(length=2, mode="sequential", case="lower")
pool.generate_library()

    name seq
0   None  aa
1   None  ac
2   None  ag
3   None  at
4   None  ca
5   None  cc
6   None  cg
7   None  ct
8   None  ga
9   None  gc
10  None  gg
11  None  gt
12  None  ta
13  None  tc
14  None  tg
15  None  tt

In [42]:
bg   = pp.from_seq("GCGC<insert2>XX</insert2>GCGC")
pool = pp.get_kmers(length=2, mode="sequential", pool=bg, region="insert2")
pool.generate_library()

    name                            seq
0   None  GCGC<insert2>AA</insert2>GCGC
1   None  GCGC<insert2>AC</insert2>GCGC
2   None  GCGC<insert2>AG</insert2>GCGC
3   None  GCGC<insert2>AT</insert2>GCGC
4   None  GCGC<insert2>CA</insert2>GCGC
5   None  GCGC<insert2>CC</insert2>GCGC
6   None  GCGC<insert2>CG</insert2>GCGC
7   None  GCGC<insert2>CT</insert2>GCGC
8   None  GCGC<insert2>GA</insert2>GCGC
9   None  GCGC<insert2>GC</insert2>GCGC
10  None  GCGC<insert2>GG</insert2>GCGC
11  None  GCGC<insert2>GT</insert2>GCGC
12  None  GCGC<insert2>TA</insert2>GCGC
13  None  GCGC<insert2>TC</insert2>GCGC
14  None  GCGC<insert2>TG</insert2>GCGC
15  None  GCGC<insert2>TT</insert2>GCGC

## Combining Pools

### join

In [49]:
left  = pp.from_seqs(["AA", "CC"], mode="sequential")
right = pp.from_seqs(["GG", "TT"], mode="sequential")   
pool  = pp.join([left, right])
pool.generate_library()

   name   seq
0  None  AAGG
1  None  AATT
2  None  CCGG
3  None  CCTT

In [59]:
left  = pp.from_seq("ACGT")
right = pp.from_seqs(["AAAA", "CCCC", "GGGG"], mode="sequential")
pool  = pp.join([left, right], spacer_str="TTT")
pool.generate_library()

   name          seq
0  None  ACGTTTTAAAA
1  None  ACGTTTTCCCC
2  None  ACGTTTTGGGG

In [56]:
a    = pp.from_seqs(["A", "C"], mode= 'sequential', iter_order=2)   # outer (slower)
b    = pp.from_seqs(["G", "T"], mode='sequential', iter_order=1)   # inner (faster)
pool = pp.join([a, b])
pool.generate_library()

   name seq
0  None  AG
1  None  AT
2  None  CG
3  None  CT

In [61]:
promoter = pp.from_seqs(["AAAA", "CCCC"], mode="sequential")
insert   = pp.from_seqs(["GCGC", "TATA"], mode="sequential")
pool     = pp.join([promoter, "NNNNN", insert])
pool.generate_library()

   name            seq
0  None  AAAANNNNNGCGC
1  None  AAAANNNNNTATA
2  None  CCCCNNNNNGCGC
3  None  CCCCNNNNNTATA

### Concatenation operators

In [ ]:
wt   = pp.from_seq("ATCG")
muts = pp.mutagenize(wt, num_mutations=1, mode="sequential")
ctrl = pp.from_seqs(["AAAA", "TTTT"], mode="sequential")
lib  = muts + ctrl   # all single-point mutants + 2 controls
lib.generate_library()
muts.generate_library()

    name   seq
0   None  CTCG
1   None  GTCG
2   None  TTCG
3   None  AACG
4   None  ACCG
5   None  AGCG
6   None  ATAG
7   None  ATGG
8   None  ATTG
9   None  ATCA
10  None  ATCC
11  None  ATCT

In [ ]:
unit = pp.from_seqs(["AT", "CG"], mode="sequential")
pool = unit * 3
pool.generate_library()

   name seq
0  None  AT
1  None  AT
2  None  AT
3  None  CG
4  None  CG
5  None  CG